Update myMathSheets_test.yml

diff --git a/.github/workflows/myMathSheets_test.yml b/.github/workflows/myMathSheets_test.yml
--- a/.github/workflows/myMathSheets_test.yml
+++ b/.github/workflows/myMathSheets_test.yml
@@ -52,37 +52,42 @@ jobs:
       working-directory: ${{ env.WORKING_DIR }}
       run: |
         dotnet test ./CommonLibTest/MyMathSheets.CommonLibTest.csproj --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" /p:CollectCoverage=true /p:MergeWith=${{ env.OUTPUT_DIR }}/coverage.json /p:CoverletOutput=${{ env.OUTPUT_DIR }}/ --% /p:CoverletOutputFormat=\"cobertura,json\"
-    
-    - name: Create unit test report
-      uses: dorny/test-reporter@v1
-      if: always()
-      with:
-          name: NUnit report
-          path: "test-results.trx"
-          reporter: dotnet-trx
-          only-summary: 'false'
-          fail-on-error: 'false'
-          working-directory: ${{ env.WORKING_DIR }}
-          
-    - name: Archive nunit test artifacts
-      if: always()
-      continue-on-error: true
-      uses: actions/upload-artifact@v2
-      with:
-        name: NUnitTestLog
-        path: |
-          ${{ env.WORKING_DIR }}/test-results.trx
-        retention-days: 30
+        if (-Not $?) {
+          exit 1
+        } else {
+          exit 0
+        }
         
-    - name: Create coverage report
-      if: always()
-      continue-on-error: true
-      run: |
-        reportgenerator -reports:${{ env.OUTPUT_DIR }}/coverage.cobertura.xml -targetdir:${{ env.REPORT_DIR }} -reporttypes:Html
+    #- name: Create unit test report
+    #  uses: dorny/test-reporter@v1
+    #  if: always()
+    #  with:
+    #      name: NUnit report
+    #      path: "test-results.trx"
+    #      reporter: dotnet-trx
+    #      only-summary: 'false'
+    #      fail-on-error: 'false'
+    #      working-directory: ${{ env.WORKING_DIR }}
+          
+    #- name: Archive nunit test artifacts
+    #  if: always()
+    #  continue-on-error: true
+    #  uses: actions/upload-artifact@v2
+    #  with:
+    #    name: NUnitTestLog
+    #    path: |
+    #      ${{ env.WORKING_DIR }}/test-results.trx
+    #    retention-days: 30
+        
+    #- name: Create coverage report
+    #  if: always()
+    #  continue-on-error: true
+    #  run: |
+    #    reportgenerator -reports:${{ env.OUTPUT_DIR }}/coverage.cobertura.xml -targetdir:${{ env.REPORT_DIR }} -reporttypes:Html
 
-    - name: Archive coverage report artifacts
-      uses: actions/upload-artifact@v2
-      with:
-        name: UnitTestCoverageReport
-        path: ${{ env.REPORT_DIR }}
-        retention-days: 30
+    #- name: Archive coverage report artifacts
+    #  uses: actions/upload-artifact@v2
+    #  with:
+    #    name: UnitTestCoverageReport
+    #    path: ${{ env.REPORT_DIR }}
+    #    retention-days: 30
